### ISSUE TITLE
Instructions to implement in existing project

### ISSUE THREAD

**Issue by bradherman** [dixahq/dixa-messenger-react-native-demo#3]
It would be great if there were some step by step instructions on implementing this for iOS and Android in an existing RN project.  Thanks!

**Comment by professorkolik** [comment]
Any update on this?

**Comment by idortulov** [comment]
@bradherman, @professorkolik Did you try the instructions from https://messenger-docs.dixa.io/android/cross-platform?

**Comment by professorkolik** [comment]
@idortulov  Yes, found later

**Comment by idortulov** [comment]
@professorkolik Do you have any additional questions? Or can we close this ticket?

**Comment by professorkolik** [comment]
@idortulov nope, all clear with instructions
